#!/usr/bin/env python3
"""Build a single self-contained lha-app.html.

The app loads ladder-data.js and timing.js as separate files, which is right
for the site and wrong for a file somebody opens from Finder: any path
problem, any stale copy of one of the three, and the app throws before it
draws. This inlines them so there is one file that cannot be half updated
and cannot fail to find its own data.

Generated, never edited by hand. Re-run after changing any of the three.
"""
import io, os, re, sys, datetime

SRC = os.path.expanduser('~/lha')
out_path = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser(
    '~/Downloads/LHA-APP-OPEN-THIS.html')

PAGE = sys.argv[2] if len(sys.argv) > 2 else 'lha-app.html'
html = io.open(os.path.join(SRC, PAGE), encoding='utf-8').read()
for name in ('ladder-data.js', 'timing.js'):
    js = io.open(os.path.join(SRC, name), encoding='utf-8').read()
    tag = '<script src="%s"></script>' % name
    if tag not in html:
        sys.exit('cannot find %s in lha-app.html' % tag)
    html = html.replace(tag, '<script>/* inlined %s */\n%s\n</script>' % (name, js))

stamp = datetime.datetime.now().strftime('%d %B %Y at %H:%M')
html = html.replace('<head>',
    '<head>\n<!-- SELF CONTAINED BUILD, %s. ladder-data.js and timing.js are\n'
    '     inlined above the app script. Generated by tools/make-standalone.py;\n'
    '     edit ~/lha/lha-app.html, not this. -->' % stamp, 1)

io.open(out_path, 'w', encoding='utf-8').write(html)
print('%s  %.0f KB' % (out_path, os.path.getsize(out_path)/1024))
